name: Test Docker Hub Push

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: geraldpascual30/practica-entrega-continua

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar secrets
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          if [ -z "$DOCKERHUB_USERNAME" ]; then
            echo "DOCKERHUB_USERNAME VACIO"
            exit 1
          fi
          if [ -z "$DOCKERHUB_TOKEN" ]; then
            echo "DOCKERHUB_TOKEN VACIO"
            exit 1
          fi
          echo "Secrets OK"

      - name: Docker login manual
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Push image
        run: docker push $IMAGE_NAME:latest
